### ISSUE TITLE
spei and pep

### ISSUE THREAD

**Issue by fipoucat** [adrfantini/ncspiR#4]
Hi, 

I am wondering if it is possible to compute potential evapotranspiration (pep) using nc file of tmean, tmin and tmax?

**Comment by adrfantini** [comment]
It's out of scope for this small tool, sorry.

The variable you are looking for can be calculated from basic data (not just temperature afaik, though), but there are several methods to do so and the results can vary greatly.
See here: https://en.wikipedia.org/wiki/Potential_evaporation
